In [1]:
#pip install numpy

In [2]:
import numpy as np

Numpy Arrays
* list
* arange()
* linspace()
* zeros()
* ones()
* empty()
* random()

In [3]:
list = list(range(1, 7))
list

[1, 2, 3, 4, 5, 6]

In [5]:
arr = np.array(list)
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr.ndim

1

In [8]:
arr[-1]

np.int64(6)

In [9]:
arr[:]

array([1, 2, 3, 4, 5, 6])

In [11]:
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [12]:
arr.shape

(6,)

In [19]:
arr2d = arr.reshape(2,3)

In [20]:
arr2d.shape

(2, 3)

In [21]:
arr2d.size

6

In [22]:
arr2d.ndim

2

In [32]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2d[1][0]

np.int64(4)

In [38]:
arr2d[1, 0]

np.int64(4)

In [53]:
### np.arange()

arange = np.arange(1, 5, 0.5, dtype='float')
arange

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [68]:
arange = np.arange(1, 28).reshape(3, 3, 3)
arange

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [81]:
np.linspace(1, 20, num=100).reshape(10, 10)

array([[ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
         1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273],
       [ 2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
         3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465],
       [ 4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
         5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657],
       [ 6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
         7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848],
       [ 8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
         9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ],
       [10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
        11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232],
       [12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
        13.47474747, 13.66666667, 13.85858586

In [87]:
np.zeros((1000, 1000))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [96]:
ones = np.ones((10, 10))*36

In [97]:
ones[0] = 93

In [98]:
ones

array([[93., 93., 93., 93., 93., 93., 93., 93., 93., 93.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.]])

In [99]:
ones[-1] = -93
ones

array([[ 93.,  93.,  93.,  93.,  93.,  93.,  93.,  93.,  93.,  93.],
       [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
       [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
       [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
       [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
       [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
       [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
       [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
       [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
       [-93., -93., -93., -93., -93., -93., -93., -93., -93., -93.]])

In [102]:
np.empty((3, 3))

array([[0.0e+000, 4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323, 2.5e-323],
       [3.0e-323, 3.5e-323, 4.0e-323]])

In [103]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
np.random.rand(20)

array([0.92991104, 0.91609197, 0.43045577, 0.19811917, 0.29583602,
       0.71556861, 0.29691456, 0.84429428, 0.73887216, 0.72951713,
       0.84967032, 0.0303658 , 0.82660856, 0.87982721, 0.96261236,
       0.32557283, 0.29528531, 0.13596418, 0.85348868, 0.85748143])

In [108]:
np.random.rand(2, 2)

array([[0.22096372, 0.50228683],
       [0.11352825, 0.51296021]])

In [534]:
#standard normal distribution (0 mean, 1 variance )
np.random.randn(100, 100)

array([[-0.56485282,  0.56162827,  1.53104927, ...,  1.4566461 ,
         0.15582884, -0.64834429],
       [ 0.2516443 , -0.75600375, -2.86303579, ...,  0.34753126,
         0.44025563,  1.82851685],
       [-0.06502178,  1.42280555,  0.37227723, ...,  1.42203969,
        -0.64362941,  0.11359128],
       ...,
       [ 0.15976512, -0.52954512, -0.19960613, ..., -0.30944563,
         0.70607656, -0.02188763],
       [ 0.51081368, -0.56810926, -0.06059113, ..., -0.6669812 ,
         0.96471604,  0.06991935],
       [ 1.39231782, -0.42612635, -2.3329994 , ...,  1.02019177,
         1.02378093,  1.35079924]])

In [3]:
data = np.random.randint(199, size=(100, 100))

In [4]:
data.max()

np.int64(198)

In [5]:
data.sum()

np.int64(989243)

In [7]:
data.argmin()

np.int64(209)

In [8]:
print(np.random.random(1), np.random.rand(1), np.random.random_sample(1))

[0.39056224] [0.73277755] [0.24715272]


In [148]:
data = np.random.rand(2, 3)
data


array([[0.7049394 , 0.03257365, 0.30319859],
       [0.02918494, 0.93503372, 0.20967048]])

In [17]:
data.transpose()

array([[0.17000232, 0.91318544],
       [0.70487029, 0.81979553],
       [0.04651481, 0.43595429]])