# NumPy Exercises Part -1 

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array from the following list 
lst = [1,2,5,7]

In [2]:
lst = [1, 2, 5, 7]

In [3]:
np.array(lst)

array([1, 2, 5, 7])

#### Create a 2x2 marix like the below cell

In [24]:
x = np.arange(10, 100, 10).reshape(3, 3)
x[-1] = x[-1]+1

x

array([[10, 20, 30],
       [40, 50, 60],
       [71, 81, 91]])

#### Create an array of 5 zeros 

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### Create an array of 4x4 ones

In [6]:
ones = np.ones((4, 4))

#### Create an 4x4 array of containing all fours

In [7]:
np.ones((4, 4))*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

#### Create a 5x5 identity matrix 

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Create an array of the integers from 5 to 50

In [9]:
np.arange(5, 51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 0 to 50

In [10]:
np.arange(0, 51, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

#### Create a 4x4 matrix with values ranging from 0 to 16

In [11]:
np.arange(0, 16).reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Use NumPy to generate 2 random numbers in the [0,1] interval

In [12]:
np.random.rand(2)

array([0.55244247, 0.40666129])

In [13]:
lst = ([1, 2, 5, 7])
lst

[1, 2, 5, 7]

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution and show in 5X5 form

In [14]:
np.random.standard_normal(25).reshape(5, 5)

array([[-0.82041804,  1.09073818,  0.58397174, -2.71288841, -0.50835897],
       [ 0.48825922,  2.02498155, -0.1208354 ,  1.32535111, -0.56637082],
       [ 0.52228636, -0.19682806, -1.09115576,  0.81747282, -2.00695878],
       [ 1.2576879 ,  1.605095  ,  0.84650572,  0.64455888, -0.67620887],
       [ 0.6986221 , -0.52262818, -2.53769988,  0.03318412, -2.25150247]])

#### Create the following matrix: 
[hint: you can use arange method] 

In [15]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 25 linearly spaced points between 0 and 1:

In [16]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

## Generate 10 random interger numbers from 0 to 100 and assign to arr array

In [17]:
arr = np.random.randint(0, 100, 10)
arr

array([75, 28, 82, 48, 70, 55, 73, 69,  7, 96])

array([25, 99, 74, 85, 79, 88, 48, 49, 35, 89])

### find max value in arr

In [18]:
arr.max()

np.int64(96)

### find min value in arr

In [19]:
arr.min()

np.int64(7)

### find max value index in arr

In [20]:
np.argmax(arr)

np.int64(9)

### find min value index in arr

In [21]:
np.argmin(arr)

np.int64(8)

# Good Job!